# 
# TESTBASE API Version Configuration
# 
#     !!! Should be modified according to the API !!!
# 
set(${MODULE_UPPER_NAME}_VERSION_MAJOR 3)
set(${MODULE_UPPER_NAME}_VERSION_MINOR 1)
set(${MODULE_UPPER_NAME}_VERSION_REVISION 0)

# Make version string
set(${MODULE_UPPER_NAME}_VERSION ${${MODULE_UPPER_NAME}_VERSION_MAJOR}.${${MODULE_UPPER_NAME}_VERSION_MINOR}.${${MODULE_UPPER_NAME}_VERSION_REVISION})

include(${PROJECT_SOURCE_DIR}/cmake/TESTBASE.cmake)
# Add specific device list
# Format: {DEVICE_TYPE, HW_VERSION_MAJOR, HW_VERSION_MINOR, HW_VERSION_REVISION, FW_VERSION_MAJOR, FW_VERSION_MINOR, FW_VERSION_REVISION}
# 
# DEVICE_TYPE:  
#   TESTBASE_DEVICE_TYPE_CPCIE
#   TESTBASE_DEVICE_TYPE_PCIE
#   TESTBASE_DEVICE_TYPE_PCIE_EXIO
#   TESTBASE_DEVICE_TYPE_USB

# 
# TESTBASE API compatibility configuration
# 
#     !!! Should be modified according to the API !!!
# 
set(${MODULE_UPPER_NAME}_DEVICE_SUPPORT 
    "{${TESTBASE_DEVICE_TYPE_CPCIE},2,1,0,7,0,0}"
)

set(${MODULE_UPPER_NAME}_DRIVER_USE "xdma")